FROM python:3.9

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt
RUN apk add tesseract-ocr-por

COPY . .

ENV IP_ADDRESS_CONTAINER_RABBITMQ = "172.23.0.2"

CMD ["python", "main.py"]
